// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbC9HD6-Xd7DzM7Tg2QTJGmpQgyq8uU0',
    appId: '1:449658428178:web:a2d567173a042b8ffff1cb',
    messagingSenderId: '449658428178',
    projectId: 'kaamquest',
    authDomain: 'kaamquest.firebaseapp.com',
    storageBucket: 'kaamquest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzujdZfWAlv6W0RMRWBmObWENprcS0lNM',
    appId: '1:449658428178:android:7d334653c26df131fff1cb',
    messagingSenderId: '449658428178',
    projectId: 'kaamquest',
    storageBucket: 'kaamquest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1ZzDpovBmRPybOXhg9ArCR1kdTtHiR8',
    appId: '1:449658428178:ios:b59bab39a02e7f76fff1cb',
    messagingSenderId: '449658428178',
    projectId: 'kaamquest',
    storageBucket: 'kaamquest.appspot.com',
    iosClientId:
        '449658428178-sog8no3u7f8l314bde3smef00qqc20t3.apps.googleusercontent.com',
    iosBundleId: 'com.pnn.kaamQuest',
  );
}
